global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iris-api'
    static_configs:
      - targets: ['host.docker.internal:8000']  # For Mac/Windows
        # Use 'docker.for.mac.localhost' for older Docker Mac versions
        # Use 'docker.for.win.localhost' for Windows
